name: Main CI
  
on:
  push:
    branches: 
      - master
  schedule:
   - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  extract_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: ./
      
      - name: Checkout nytimes repo
        uses: actions/checkout@v2
        with:
          repository: nytimes/covid-19-data
          path: ./csv
     
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install modules
        run: npm install
        env:
          CI: true 
      
      - name: Run main.js to extract JSON
        run: npm run start

      - name: Make README.MD for csv folder
        run: |
          cd csv
          echo -e "# Required Files \nThis project requires \`us-states.csv\` and \`us-counties.csv\` from [nytimes/covid-19-data](https://github.com/nytimes/covid-19-data). \n \nIf you wish to run this locally, please download \`us-states.csv\` and \`us-counties.csv\`, then place them in this folder. \n \nThe Github Action is setup to do this automatically and generate the \`timeseries.json\` and \`timeseries-counties.json\` file." > README.md
          cd ..
          
      - name: Commit timeseries.json, timeseries-counties.json, ./csv/README.md
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./docs/timeseries.json
          git add ./docs/timeseries-counties.json
          git add ./csv/README.md
          git diff-index --quiet HEAD || git commit -m "Updated timeseries.json and timeseries-counties.json" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: ./
